# Continuous Integration Workflow, will build applications, publish artifacts and deploy to Azure
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/azure.yml'
      - 'src/**'

env:
  RESOURCE_GROUP_NAME: "hamrwa-rg"
  FIRST_LOCATION: "EastUS"
  SECOND_LOCATION: "WestUS2"
  PREFIX: "hamrwa"
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Calculate Timestamp
        id: timestamp
        run: |
          timestamp=$(date -u -d '%Y%m%d%H%M')
          echo "::set-output name=value::$timestamp"

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Create Resource Groups
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create -l ${{ env.FIRST_LOCATION }} -n ${{env.RESOURCE_GROUP_NAME}}

      - name: Deploy ARM Template
        id: arm
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          region: ${{ env.FIRST_LOCATION }}
          template: src/templates/azure.deploy.json
          parameters: FirstRegionLocation=${{ env.FIRST_LOCATION }} SecondRegionLocation=${{ env.SECOND_LOCATION }}
          deploymentName: ${{ env.PREFIX }}.${{ deploy.timestamp.outputs.value }}
