# Continuous Integration Workflow, will build applications, publish artifacts and deploy to Azure
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/azure.yml'
      - 'src/**'

env:
  FIRST_LOCATION: "EastUS"
  SECOND_LOCATION: "WestUS2"
  PREFIX: "hamrwa"
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Calculate SAS Token Expiration
        id: expiry
        run: |
          end=$(date -u -d "6 hours" '+%Y-%m-%dT%H:%MZ')
          echo "::set-output name=end::$end"

      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload Region Templates
        id: templateupload
        uses: azure/CLI@v1
        with:
          inlineScript: |
            name='${{env.PREFIX}}.region.deploy.json'
            az storage blob upload --container-name templates --file src/templates/region.deploy.json --name $name
            echo "Token will expire on ${{ steps.expiry.outputs.end }}"
            uri=$(az storage blob generate-sas --container-name templates --name $name --permissions r --expiry ${{ steps.expiry.outputs.end }} --full-uri --https-only -o tsv)
            echo "::set-output name=templateuri::$uri"

      - name: Print GITHUB_RUN_NUMBER
        run: echo ${{process.env.GITHUB_RUN_NUMBER}}

      - name: Deploy ARM Template
        id: arm
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          region: ${{ env.FIRST_LOCATION }}
          template: src/templates/azure.deploy.json
          parameters: ResourceGroupTemplateUri=${{ steps.templateupload.outputs.templateuri }} FirstRegionLocation=${{ env.FIRST_LOCATION }} SecondRegionLocation=${{ env.SECOND_LOCATION }}
          deploymentName: azure.deploy.${{process.env.GITHUB_RUN_NUMBER}}